"""Mathematical numeric domains, classification, and representation descriptors."""

from .arithmetic import add, common_dtype, divide, multiply, subtract
from .casting import cast
from .complex import ComplexValue
from .dtype import (
    Backend,
    ByteOrder,
    DType,
    ExactDType,
    FixedDType,
    FloatingInfo,
    IntegerInfo,
    NumericKind,
    NumPyDType,
)
from .fixed import FixedValue
from .floating import FloatingValue, PrecisionLossError, UnderflowError
from .integer import IntegerValue
from .number import (
    Algebraic,
    AlgebraicIrrational,
    Classification,
    ClassificationConflictError,
    Complex,
    IndeterminateError,
    IndeterminateMembershipError,
    IndeterminateRelationError,
    Integer,
    Irrational,
    Natural,
    Number,
    NumberSetMeta,
    Rational,
    Real,
    RealAlgebraic,
    RealTranscendental,
    Transcendental,
    Truth,
    Whole,
    classify,
    register_subset,
)
from .rational import RationalValue
from .storage import NumericBuffer

__all__ = [
    "Algebraic",
    "AlgebraicIrrational",
    "Backend",
    "ByteOrder",
    "Classification",
    "ClassificationConflictError",
    "Complex",
    "ComplexValue",
    "DType",
    "ExactDType",
    "FixedDType",
    "FixedValue",
    "FloatingInfo",
    "FloatingValue",
    "IndeterminateError",
    "IndeterminateMembershipError",
    "IndeterminateRelationError",
    "Integer",
    "IntegerInfo",
    "IntegerValue",
    "Irrational",
    "Natural",
    "NumPyDType",
    "Number",
    "NumberSetMeta",
    "NumericBuffer",
    "NumericKind",
    "PrecisionLossError",
    "Rational",
    "RationalValue",
    "Real",
    "RealAlgebraic",
    "RealTranscendental",
    "Transcendental",
    "Truth",
    "UnderflowError",
    "Whole",
    "add",
    "cast",
    "classify",
    "common_dtype",
    "divide",
    "multiply",
    "register_subset",
    "subtract",
]
